[package]
name          = "configured"
version       = "0.4.1-alpha.0"
edition       = "2021"
description   = "Utility to load configuration from three well defined layers into any type which can be deserialized by Serde"
authors       = [ "Heiko Seeberger <git@heikoseeberger.de>" ]
license-file  = "LICENSE"
readme        = "README.md"
homepage      = "https://github.com/hseeberger/configured"
repository    = "https://github.com/hseeberger/configured"
documentation = "https://github.com/hseeberger/configured"

[dependencies]
config    = "0"
serde     = "1"
thiserror = "1"

[dev-dependencies]
serde_derive = "1"
